### ISSUE TITLE
git:remote (and probably others) don't support different clouds

### ISSUE THREAD

**Issue by freeformz** [heroku/heroku-git#2]
this makes it useless with devclouds, where I want it most.

**Comment by freeformz** [comment]
AFAICT none of the node js plugin stuff supports HEROKU_API_URL or HEROKU_HOST :-(

**Comment by jdx** [comment]
can you give me an example of what isn't working exactly? It should support `HEROKU_HOST` at least.

**Comment by freeformz** [comment]
boot a devcloud and then...

``` bash
cloud $YOUR_CLOUD
heroku list
...a bunch of apps...
heroku git:remote -a <one of those apps>
 !    Couldn't find that app. OR (unauthorized error)
```

**Comment by jdx** [comment]
I'm in the process of setting up my devcloud to test, but I attempted to fix this
