### ISSUE TITLE
herokut-git error in module.js line 339

### ISSUE THREAD

**Issue by meisyal** [heroku/heroku-git#4]
Hello all,

I would like to push my application into Heroku using Heroku Toolbelt. When I was running command `heroku git:remote -a app-name`. I got this following error:

```
!     Error in heroku-git:
!     module.js:339
     throw err;
           ^
Cannot find module 'concat-stream'
Attempting to repair heroku-git...
Repair complete. Try running your command again.
```

Detail of my Heroku CLI:

```
heroku/toolbelt/3.39.1 (ruby 2.1.6)
heroku-cli/4.19.21-6f3a17a (go 1.4.2)
heroku-git@2.2.3
Windows 7 64-bit.
```

I am trying to run that command above again. Unfortunately, I always get that error.

Thank you for response.

**Comment by jdx** [comment]
can you try deleting `~/.heroku/.npm-cache` and retrying?

**Comment by meisyal** [comment]
I deleted `~/.heroku/.npm-cache` and restarted my command prompt. But, I got this error below:

```
!     Error in heroku-git:
!     module.js:339
     throw err;
           ^
Cannot find module 'co'
Attempting to repair heroku-git...
Repair complete. Try running your command again.
```

**Comment by jdx** [comment]
I put some debugging around this. Can you update with `heroku update` and try again with `GODE_DEBUG=1`?

**Comment by meisyal** [comment]
Where should I put/edit `GODE_DEBUG=1`?
I will try it.

**Comment by meisyal** [comment]
Hi @dickeyxxx. I have solved this problem by changing my environment from Windows to Linux.
I gave up how to handle it in Windows. By the way, thanks for your help.
